### PR TITLE
Added new emoji option choices, Added tests for new emojis, Updated R…

### PR DESCRIPTION
**Pull request by gitdagray**
I like reading-duration and am using it on my blog. Good work! 🙌

I thought it could support more emoji options, so here is what I added:
- Added new emoji option choices supported by emoji: boolean | string
- Added tests for new emojis
- Updated README to reflect new emoji option values

### CODE REVIEW

**Comment by mutasim77** [comment]
Hey Dave, it's great to see you here, and thank you for contributing. I really appreciate it. Yeah, a list of emojis by choice sounds like a good idea. I'll go ahead and merge it.

**Comment by gitdagray** [comment]
Thanks! I like the package and had already integrated it into my blog.

Good work!

I also wrote a post about how to use it. I will update the blog post and my
blog with the new settings.

Dave
https://www.davegray.codes/

**Comment by gitdagray** [comment]
Hi Mutasim - Hope you are doing well. Quick suggestion to update the
semantic version number of the release (currently 1.1.1) and publish the
updates to npm. Thanks!

Dave
https://www.davegray.codes/

**Comment by mutasim77** [comment]
Hey Dave, thx for reminding me. I completely forgot to do that.

**Pull request merged**
